# Generated by Django 3.2.12 on 2023-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_tm', models.DateTimeField(auto_now=True)),
                ('created_tm', models.DateTimeField(auto_now_add=True)),
                ('module_img', models.ImageField(blank=True, null=True, upload_to='./img', verbose_name='module')),
                ('module_url', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': '模块详情信息',
                'verbose_name_plural': '模块详情信息',
                'db_table': 'module_detail',
            },
        ),
    ]
