# Generated by Django 3.2.12 on 2022-09-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_date_tm',
            field=models.CharField(default='1664121600000', help_text='时间', max_length=128),
        ),
    ]
