# Generated by Django 3.2.12 on 2022-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0002_account_created_date_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_date_bj',
            field=models.CharField(default='2022-09-26 15:45:01', help_text='时间', max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date_tm',
            field=models.CharField(default=1664178301064, help_text='时间', max_length=128),
        ),
    ]
