# Generated by Django 3.2.12 on 2022-09-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0003_auto_20220926_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date_bj',
            field=models.CharField(default='2022-09-26 16:09:22', help_text='时间', max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date_tm',
            field=models.CharField(default=1664179762889, help_text='时间', max_length=128),
        ),
    ]
