# Generated by Django 3.2.12 on 2022-09-26 16:14

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_list', '0004_auto_20220926_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_tm',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default='2022-09-26 15:45:27.229127'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date_bj',
            field=models.CharField(default='2022-09-26 16:13:46', help_text='时间', max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date_tm',
            field=models.CharField(default=1664180026535, help_text='时间', max_length=128),
        ),
    ]
